start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-12" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-12"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-16" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-16"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-17" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-17"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-18" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-18"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-19" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-19"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-22" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-22"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-24" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-24"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-25" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-25"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-02-26" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-02-26"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-01" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-01"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-02" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-02"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-03" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-03"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-04" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-04"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-05" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-05"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-08" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-08"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-09" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-09"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-10" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-10"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-11" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-11"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-12" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-12"
timeout /T 2 /NOBREAK                                                                                                                                                                                                      
start ..\TradingBot\bin\Release\netcoreapp3.1\TradingBot.exe mode="TestMode" CandlesPath="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new\quotes_2021-03-15" OutputFolder="C:\tinkoff\TestData\RawQuotes\5m\uncompressed\new_corrected\quotes_2021-03-15"